basePath: /
definitions:
  dto.CapacityData:
    properties:
      code:
        type: string
      created_by:
        type: integer
      description:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      updated_by:
        type: integer
    type: object
  dto.CapacityInput:
    properties:
      code:
        type: string
      description:
        type: string
      is_active:
        type: boolean
      name:
        type: string
    type: object
  dto.CapacityOutput:
    properties:
      data:
        $ref: '#/definitions/dto.CapacityData'
    type: object
  dto.ListCapacityOutput:
    properties:
      content:
        items:
          $ref: '#/definitions/dto.CapacityData'
        type: array
      page:
        type: integer
      size:
        type: integer
      sort:
        type: string
      total:
        type: integer
      total_pages:
        type: integer
    type: object
host: localhost:8099
info:
  contact:
    email: namnguyenthanh024@gmail.com
    name: Nguyen Thanh Nam
  description: This is Sample Service API By Layer.
  title: Sample Service API By Layer
  version: "1.0"
paths:
  /api/v1/capacities:
    get:
      parameters:
      - default: 1
        description: page
        in: query
        name: page
        type: integer
      - default: 10
        description: size
        in: query
        name: size
        type: integer
      - default: created_at desc
        description: sort
        in: query
        name: sort
        type: string
      - description: search
        in: query
        name: search
        type: string
      - description: is_active
        in: query
        name: is_active
        type: string
      - description: capacity_group_ids[]
        in: query
        name: capacity_group_ids[]
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListCapacityOutput'
        "500":
          description: '{"error_code": "<Mã lỗi>", "error_msg": "<Nội dung lỗi>"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get list capacity
      tags:
      - Capacity
    post:
      consumes:
      - application/json
      description: Create new capacity
      parameters:
      - description: JSON body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CapacityInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CapacityOutput'
        "500":
          description: '{"error_code": "<Mã lỗi>", "error_msg": "<Nội dung lỗi>"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create new capacity
      tags:
      - Capacity
  /api/v1/capacities/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Capacity
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: '{"error_code": "<Mã lỗi>", "error_msg": "<Nội dung lỗi>"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Capacity
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CapacityOutput'
        "500":
          description: '{"error_code": "<Mã lỗi>", "error_msg": "<Nội dung lỗi>"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get info capacity
      tags:
      - Capacity
    put:
      consumes:
      - application/json
      description: Update capacity
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: JSON body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CapacityInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CapacityOutput'
        "500":
          description: '{"error_code": "<Mã lỗi>", "error_msg": "<Nội dung lỗi>"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update capacity
      tags:
      - Capacity
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
